name: flutter_clean
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  test: 
  faker:

flutter:
  uses-material-design: true